
build:
  script:
    - |
      if (-not (Test-Path "$pwd\java\zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64")) {
        echo "Downloading Java 8 JDK+FX"
        $global:ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Verbose -Uri http://p2.ci.bestsolution.at/jdks/win64/zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64.zip -OutFile jdk8fx.zip
        echo "Extracting..."
        Expand-Archive jdk8fx.zip -DestinationPath java
      }
      $env:JAVA_HOME = "$pwd\java\zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64"
    - Import-Module "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
    - Enter-VsDevShell -VsInstallPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
    - ./gradlew --no-daemon assemble
  tags:
    - win64
