
build:
  script:
     - Invoke-WebRequest -Verbose -Uri http://ipv4.download.thinkbroadband.com/5MB.zip -OutFile test.zip
     - rm test.zip
#    - Invoke-WebRequest -Uri https://cdn.azul.com/zulu/bin/zulu11.48.21-ca-jre11.0.11-win_x64.zip -OutFile jre11.zip
#    - Expand-Archive jre11.zip -DestinationPath java
#    - $env:JAVA_HOME = "$pwd\java\zulu11.48.21-ca-jre11.0.11-win_x64"    
    - |
      if (-not (Test-Path "$pwd\java\zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64")) {
        echo "Downloading Java 8 JDK+FX"
        Invoke-WebRequest -Verbose -Uri https://cdn.azul.com/zulu/bin/zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64.zip -OutFile jdk8fx.zip
        echo "Extracting..."
        Expand-Archive jdk8fx.zip -DestinationPath java
      }
      $env:JAVA_HOME = "$pwd\java\zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64"
    - ./gradlew assemble
  tags:
    - win64
