image: nexus.ci.bestsolution.at:8083/maven:3.6.3-jdk-11-slim

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - |
      if (-not (Test-Path "$pwd\java\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64")) {
        echo "Downloading Java 8 JDK+FX"
        $global:ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Verbose -Uri http://p2.ci.bestsolution.at/jdks/win64/zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64.zip -OutFile jdk8fx.zip
        echo "Extracting..."
        Expand-Archive jdk8fx.zip -DestinationPath java
      }
      $env:JAVA_HOME = "$pwd\java\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64"
      $env:JDK8FX = "$pwd\java\zulu8.68.0.21-ca-fx-jdk8.0.362-win_x64"
    - Import-Module "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
    - Enter-VsDevShell -VsInstallPath "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
  script:
    - ./gradlew --no-daemon assemble phatJar
  tags:
    - win64ps
  artifacts:
    paths:
      - UIAPlatform.agent/build
      - UIAPlatform.core/build
      - UIAPlatform/build
      - UIAPlatform.native/build
      - UIAPlatform.logger/build
      - UIAPlatform.sample/build
    expire_in: 10 mins


deploy_snapshot:
  stage: deploy
  only:
    - master
  script:
    - export DEPLOY_VERSION="999.0.0-`date "+%s" -d "$CI_COMMIT_TIMESTAMP"`"
    # for now we overwrite the timestamp with snapshot, need to figure out how to set all artifacts to the same timestamp -.-
    - export DEPLOY_VERSION="999.0.0-SNAPSHOT"
    - echo "Running deploy_snapshot for master DEPLOY_VERSION = $DEPLOY_VERSION"
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/snapshots/ -DrepositoryId=$MAVEN_REPO_ID-snapshots -Dfile=UIAPlatform.agent/build/libs/UIAPlatform.agent.jar -Dsources=UIAPlatform.agent/build/libs/UIAPlatform.agent-sources.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.agent -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/snapshots/ -DrepositoryId=$MAVEN_REPO_ID-snapshots -Dfile=UIAPlatform.core/build/libs/UIAPlatform.core.jar -Dsources=UIAPlatform.core/build/libs/UIAPlatform.core-sources.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.core -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/snapshots/ -DrepositoryId=$MAVEN_REPO_ID-snapshots -Dfile=UIAPlatform/build/libs/UIAPlatform.jar -Dsources=UIAPlatform/build/libs/UIAPlatform-sources.jar -Djavadoc=UIAPlatform/build/libs/UIAPlatform-javadoc.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/snapshots/ -DrepositoryId=$MAVEN_REPO_ID-snapshots -Dfile=UIAPlatform.logger/build/libs/UIAPlatform.logger.jar -Dsources=UIAPlatform.logger/build/libs/UIAPlatform.logger-sources.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.logger -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform logger support." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/snapshots/ -DrepositoryId=$MAVEN_REPO_ID-snapshots -Dfile=UIAPlatform.sample/build/libs/UIAPlatform.sample.jar -Dsources=UIAPlatform.sample/build/libs/UIAPlatform.sample-sources.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.sample -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform sample." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/snapshots/ -DrepositoryId=$MAVEN_REPO_ID-snapshots -Dfile=UIAPlatform.sample/build/libs/launcher.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.fullsample -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform full sample. This is a self running sample." 
    
  tags:
    - deploy-mvn

deploy_release:
  stage: deploy
  only:
    - /^r[0-9]+[.][0-9]+[.][0-9]+([-](m|rc)[0-9]+)?$/
  script:
    - export DEPLOY_VERSION="`echo "$CI_COMMIT_TAG" | sed -r "s/r([0-9]+[.][0-9]+[.][0-9]+([-](m|rc)[0-9]+)?)/\1/g"`"
    - echo "Running deploy_release for $CI_COMMIT_TAG, DEPLOY_VERSION = $DEPLOY_VERSION"
    - mvn -version
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/releases/ -DrepositoryId=$MAVEN_REPO_ID-releases -Dfile=UIAPlatform.agent/build/libs/UIAPlatform.agent.jar -Dsources=UIAPlatform.agent/build/libs/UIAPlatform.agent-sources.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.agent -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/releases/ -DrepositoryId=$MAVEN_REPO_ID-releases -Dfile=UIAPlatform.core/build/libs/UIAPlatform.core.jar -Dsources=UIAPlatform.core/build/libs/UIAPlatform.core-sources.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.core -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/releases/ -DrepositoryId=$MAVEN_REPO_ID-releases -Dfile=UIAPlatform/build/libs/UIAPlatform.jar -Dsources=UIAPlatform/build/libs/UIAPlatform-sources.jar -Djavadoc=UIAPlatform/build/libs/UIAPlatform-javadoc.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/releases/ -DrepositoryId=$MAVEN_REPO_ID-releases -Dfile=UIAPlatform.logger/build/libs/UIAPlatform.logger.jar -Dsources=UIAPlatform.logger/build/libs/UIAPlatform.logger-sources.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.logger -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform logger support." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/releases/ -DrepositoryId=$MAVEN_REPO_ID-releases -Dfile=UIAPlatform.sample/build/libs/UIAPlatform.sample.jar -Dsources=UIAPlatform.sample/build/libs/UIAPlatform.sample-sources.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.sample -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform sample." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=$MAVEN_REPO_URL/releases/ -DrepositoryId=$MAVEN_REPO_ID-releases -Dfile=UIAPlatform.sample/build/libs/launcher.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.fullsample -Dversion=$DEPLOY_VERSION -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform full sample. This is a self running sample." 

  tags:
   - deploy-mvn
