image: nexus.ci.bestsolution.at:8083/maven:3.6.3-jdk-11-slim

variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"


stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - |
      if (-not (Test-Path "$pwd\java\zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64")) {
        echo "Downloading Java 8 JDK+FX"
        $global:ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest -Verbose -Uri http://p2.ci.bestsolution.at/jdks/win64/zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64.zip -OutFile jdk8fx.zip
        echo "Extracting..."
        Expand-Archive jdk8fx.zip -DestinationPath java
      }
      $env:JAVA_HOME = "$pwd\java\zulu8.54.0.21-ca-fx-jdk8.0.292-win_x64"
    - Import-Module "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\Microsoft.VisualStudio.DevShell.dll"
    - Enter-VsDevShell -VsInstallPath "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
  script:
    - ./gradlew --no-daemon assemble
  tags:
    - win64
  artifacts:
    paths:
      - UIAPlatform/build
      - UIAPlatform.native/build
      - UIAPlatform.sample/build
    expire_in: 10 mins


deploy_snapshot:
  stage: deploy
  only:
    - master
  script:
    - echo "Running deploy_snapshot for master"
    - ls UIAPlatform/build/libs/UIAPlatform.jar
    - ls UIAPlatform/build/libs/UIAPlatform-sources.jar
    - ls UIAPlatform/build/libs/UIAPlatform-javadoc.jar
    - ls UIAPlatform.sample/build/libs/UIAPlatform.sample.jar
    - ls UIAPlatform.sample/build/libs/launcher.jar
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=http://nexus.ci.bestsolution.at:8081/repository/beso-oss-snapshots/ -DrepositoryId=beso-oss-snapshots -Dfile=UIAPlatform/build/libs/UIAPlatform.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform -Dversion=9.9.9-SNAPSHOT -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=http://nexus.ci.bestsolution.at:8081/repository/beso-oss-snapshots/ -DrepositoryId=beso-oss-snapshots -Dfile=UIAPlatform/build/libs/UIAPlatform-sources.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform -Dversion=9.9.9-SNAPSHOT -Dpackaging=jar -Dclassifier=sources -DgeneratePom.description="JavaFX UIA platform." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=http://nexus.ci.bestsolution.at:8081/repository/beso-oss-snapshots/ -DrepositoryId=beso-oss-snapshots -Dfile=UIAPlatform/build/libs/UIAPlatform-javadoc.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform -Dversion=9.9.9-SNAPSHOT -Dpackaging=jar -Dclassifier=javadoc -DgeneratePom.description="JavaFX UIA platform." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=http://nexus.ci.bestsolution.at:8081/repository/beso-oss-snapshots/ -DrepositoryId=beso-oss-snapshots -Dfile=UIAPlatform.sample/build/libs/UIAPlatform.sample.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.sample -Dversion=9.9.9-SNAPSHOT -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform sample." 
    - mvn $MAVEN_CLI_OPTS deploy:deploy-file -Durl=http://nexus.ci.bestsolution.at:8081/repository/beso-oss-snapshots/ -DrepositoryId=beso-oss-snapshots -Dfile=UIAPlatform.sample/build/libs/launcher.jar -DgroupId=at.bestsolution.openfx-uia -DartifactId=UIAPlatform.fullsample -Dversion=9.9.9-SNAPSHOT -Dpackaging=jar -DgeneratePom.description="JavaFX UIA platform full sample. This is a self running sample." 
    
  tags:
    - deploy-mvn

deploy_release:
  stage: deploy
  only:
    - /^r[0-9]+[.][0-9]+[.][0-9]+(-[a-z0-9]+)?$/
  script:
    - echo "Running deploy_release for $CI_COMMIT_TAG"
    - mvn -version
    - ls UIAPlatform/build/libs/UIAPlatform.jar
    - ls UIAPlatform/build/libs/UIAPlatform-sources.jar
    - ls UIAPlatform/build/libs/UIAPlatform-javadoc.jar
    - ls UIAPlatform.sample/build/libs/UIAPlatform.sample.jar
    - ls UIAPlatform.sample/build/libs/launcher.jar
  tags:
   - deploy-mvn
